#!/usr/bin/env bash
#a counting variable initiation
counter=0

#looping condition
while [ $counter -le 19 ]
    do
      ((counter+=1)) #increase the counter by one each time through the loop.
        echo "$counter" 
        if [[ $counter == 4 ]]; 
            then
                echo "bad luck from china"
        elif [[ $counter == 9 ]]; 
            then
                echo "bad luck from japan"
        elif [[ $counter == 17 ]]; 
            then
                echo "bad luck from Italy"
        fi  
        echo -n ""    
done
