#!/usr/bin/env bash
#assigning a variable to the file
school_file="loops_conditions_and_parsing"
#checking if the file name school exist 
if [ -e "$school_file" ]; 
then
   echo  "school file exists "
#using nested if to check if the file is empty
    if [ ! -s "$school_file" ]; then
        echo -n "school File is empty."
#using nested if to check if the file is not empty
    else 
        echo -n "school File is not empty"
    fi
#using nested if to check if the file is regular
    if [ -f "$school_file" ]; then
        echo -n "school is a regular file"
#using nested if to check if the file is regular   
    else
        echo -n "" 
    fi               
else
    echo -n "school file does not exist"
fi