#!/usr/bin/env bash
# Display headers
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
# Display process hierarchy
ps axjf | awk '{printf "%-10s %7d %4.1f %4.1f %6s %6s %-8s %3s %7s %7s ", $8, $2, $3, $4, $5, $6, $7, $10, $11, $12; for (i=13; i<=NF; i++) {printf "%s ", $i}; printf "\n"}'
