#!/usr/bin/env bash

max_iterations=10
counter=0

while [ $counter -lt $max_iterations ]; do
    echo "To infinity and beyond"
    sleep 2
    ((counter++))
    if [ $counter -eq 7 ]; then
        echo -n "terminated"
        break
    fi
done